<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>appDemo</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Username</th>
        </tr>
        <?php foreach($articles as $article): ?>
            <tr>
                <td><a href="index.php?route=articleUpdateForm&articleId=<?=$article -> articleId?>"><?=$article -> title ?></a></td>
                <td><?=$article -> description ?></td>
                <td><?=$article -> username ?></td>
            </tr>
        <?php endforeach; ?>


    </table>
    <form class="" action="index.php?route=articleList" method="">
        <input type="hidden" name="route" value="articleList">
        <input type="text" name="articleFilter" value="">
        <input type="submit" name="" value="search">
    </form>
</div>











<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>
