<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body>
    <div class="container resizedForm">
        <form action="index.php?route=<?php if (!isset($category->name)): ?>categoryCreateForm<?php else: ?>categoryUpdateForm&categoryId=<?=$category->categoryId?><?php endif; ?> " method="post">
            <div class="form-group">
                <h1><?php if (!isset($category->name)):?>Add Category<?php else: ?>Edit Category<?php endif;?></h1>
                <input type="text" name="categoryName" value="<?php if (isset($category->name)){echo $category->name;}?>">
                <input type="submit" name="submit" value="Add">
            </div>
        </form>
    </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>
