<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body>
    <div class="container resizedForm">
        <form action="index.php?route=categorySave" method="post">
            <div class="form-group">
                <h1>Add Category</h1>
                <input type="text" name="category">
                <input type="submit" name="submit" value="Add">
            </div>
        </form>
        <div class="container">
            <table class="table">
                <tr>
                    <th>Category name</th>
                </tr>
                <?php foreach($categories as $category): ?>
                    <tr>
                        <td><?=$category -> category ?></td>
                    </tr>
                <?php endforeach; ?>


            </table>
    </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>
