<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign in</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <ul class="nav nav-tabs">
            <?php if (!isLoggedIn()): ?>
            <li role="navbar" class="active"><a href="index.php?route=loginForm">Login</a></li>
            <?php else: ?>
            <li><a href="index.php?route=userList&page=1">Update User</a></li>
            <li><a href="index.php?route=userCreateForm">Create User</a></li>
            <li><a href="index.php?route=articleCreateForm">Create Article</a></li>
            <li><a href="index.php?route=articleList&page=1">Update Article</a></li>
            <li><a href="index.php?route=categoryCreateForm">Create Category</a></li>
            <li><a href="index.php?route=categoryList">Update Category</a></li>
            <li class="navbar-right"><a href="index.php?route=userLogout"> Logout </a></li>
            <?php endif; ?>
        </ul
          <?php if(strlen($message)>0):?>
            <?=$message?>
          <?php endif;?>

    </div>


</body>
</html>