<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>appDemo</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
</head>
     <body>
          <div class="container">
               <div class="row align-items-center justify-content-center">
                    <div class="col-sm-6">
                         <form class="" action="index.php?route=login" method="post">
                              <h5>Login</h5>
                              <div class="form-group">
                                   <input type="email" name="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
                              </div>
                              <div class="form-group">
                                   <input type="password" name="password" class="form-control" placeholder="Password">
                              </div>

                              <button type="submit" class="btn btn-primary" style="width: 100%;">Login</button>
                         </form>
                    </div>
               </div>
          </div>












          <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
          <!-- Include all compiled plugins (below), or include individual files as needed -->
          <script src="js/bootstrap.min.js"></script>
     </body>
</html>
