<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">

    <title>appDemo</title>
</head>
<body>

<div class="container">
    <div class="row align-items-center justify-content-center">
        <div class="col-sm-6">
            <form enctype="multipart/form-data" action="index.php?route=<?php if (!isset($user->email)): ?>userCreate<?php else: ?>userUpdate<?php endif; ?> " method="post">
                    <h5><?php if(isset($user->email)): ?>Update profile<?php else: ?>Create new profile<?php endif; ?>  </h5>
                <div class="form-group">
                    <div class="form-group">
                        <input value="<?php if(isset($user->firstName)): echo $user->firstName; endif;?>" type="text" name="firstName" class="form-control" placeholder="First name">
                    </div>
                    <div class="form-group">
                        <input value="<?php if(isset($user->lastName)): echo $user->lastName; endif;?>" type="text" name="lastName" class="form-control" placeholder="Last name">
                    </div>
                    <div class="form-group">
                        <input value="<?php if(isset($user->username)): echo $user->username; endif;?>" type="text" name="username" class="form-control" placeholder="Username">
                    </div>

                   <input type="email" value="<?php if(isset($user->email)): echo $user->email; endif;?>" name="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password">
                </div>
                <div class="form-group">
                    <input type="password" name="password-2" class="form-control" placeholder="Confirm password">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="form-group">
                    <select name="status">
                        <option value="1">Active</option>
                        <option value="0">Inactive</option>
                    </select>
                </div>
                <?php if(isset($user->email)): ?><input type="hidden" name="id" value="<?=$user->id?>"><?php else: ?><?php endif; ?>



                <button type="submit" class="btn btn-primary" style="width: 100%;"><?php if (isset($user->email)):?>Update<?php else:?>Create<?php endif; ?></button>
            </form>
        </div>
    </div>
</div>













<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
