<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>appDemo</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
</head>
<body>

    <div class="container resizedForm">
        <form enctype="multipart/form-data" action="index.php?route=<?php if (!isset($user->email)): ?>userCreate<?php else: ?>userUpdate&userId=<?=$user->userId?><?php endif; ?> " method="post">
                    <h5><?php if(isset($user->email)): ?>Update profile<?php else: ?>Create new profile<?php endif; ?>  </h5>
                <div class="form-group">
                    <div class="form-group">
                        <input value="<?php if(isset($user->firstName)): echo $user->firstName; endif;?>" type="text" name="firstName" class="form-control" placeholder="First name">
                    </div>
                    <div class="form-group">
                        <input value="<?php if(isset($user->lastName)): echo $user->lastName; endif;?>" type="text" name="lastName" class="form-control" placeholder="Last name">
                    </div>
                    <div class="form-group">
                        <input value="<?php if(isset($user->username)): echo $user->username; endif;?>" type="text" name="username" class="form-control" placeholder="Username">
                    </div>

                   <input type="email" value="<?php if(isset($user->email)): echo $user->email; endif;?>" name="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password">
                </div>
                <div class="form-group">
                    <input type="password" name="password-2" class="form-control" placeholder="Confirm password">
                </div>
                <div class="form-group">
                    <label for="image">Age</label>
                    <input type="number" name="age" class="form-control">
                </div>
                <div class="form-group">
                    <select name="status">
                        <option value="1">Active</option>
                        <option value="0">Inactive</option>
                    </select>
                </div>


                <button type="submit" class="btn btn-primary" style="width: 100%;"><?php if (isset($user->email)):?>Update<?php else:?>Create<?php endif; ?></button>
            </form>
    </div>












<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>
