<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>appDemo</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
<body>
<div class="container">
    <table class="table">
        <tr>
            <th>Email</th>
            <th>First name</th>
            <th>last name</th>
            <th>Username</th>
            <th>Image</th>
        </tr>
        <?php foreach($users as $user): ?>
            <tr>
                <td><a href="index.php?route=userUpdateForm&userId=<?=$user -> userId?>"><?=$user -> email ?></a></td>
                <td><?=$user -> firstName ?></td>
                <td><?=$user -> lastName ?></td>
                <td><?=$user -> username ?></td>
                <td><img src="<?=$user -> image ?>" alt=""></td>
            </tr>
        <?php endforeach; ?>


    </table>
    <form class="" action="index.php?route=userListForm" method="">
        <input type="hidden" name="route" value="userListForm">
        <input type="text" name="emailFilter" value="">
        <input type="submit" name="" value="search">
    </form>
</div>











<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>
