<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>appDemo</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
<body>
<div class="container">
    <table class="table">
        <tr>
            <th>Email</th>
            <th>First name</th>
            <th>last name</th>
            <th>Username</th>
            <th>Image</th>
        </tr>
        <?php foreach($users as $user): ?>
            <tr>
                <td><a href="index.php?route=userUpdateForm&userId=<?=$user -> userId?>"><?=$user -> email ?></a></td>
                <td><?=$user -> firstName ?></td>
                <td><?=$user -> lastName ?></td>
                <td><?=$user -> username ?></td>
                <td><img src="<?=$user -> image ?>" alt=""></td>
            </tr>
        <?php endforeach; ?>
                <a class="btn btn-default" href="index.php?route=userList&page=<?php if($page <= 1){echo $page;}else {echo $page-1;}?>">Previous Page</a>
                <a class="btn btn-default" href="index.php?route=userList&page=<?php if($page >= $maxPages){echo $maxPages;}else {echo $page+1;}?>">Next Page</a>
                <a class="btn btn-default<?php if ($page==1)echo ' active'?>" href="index.php?route=userList&page=1">1</a><span><?php if ($page > 3) echo '...' ?></span>
                <a class="btn btn-default<?php if ($page<3)echo ' hidden'?>" href="index.php?route=userList&page=<?=$page-1?>"><?=$page-1?></a>
                <a class="btn btn-default <?php if ($page>1)echo 'active'?>" href="index.php?route=userList&page=<?php if ($page==1)echo $page+1;else echo $page?>"><?php if ($page==1)echo $page+1;else echo $page?></a>
                <a class="btn btn-default" href="index.php?route=userList&page=<?php if ($page == 1)echo $page+2;else echo $page+1;?>"><?php if ($page == 1)echo $page+2;else echo $page+1;?></a><span><?php if ($page<$maxPages)echo '...'?></span>
                <a class="btn btn-default" href="index.php?route=userList&page=<?=$maxPages?>"><?=$maxPages?></a>

    </table>
    <form class="" action="index.php?route=userListForm" method="">
        <input type="hidden" name="route" value="userListForm">
        <input type="text" name="emailFilter" value="">
        <input type="submit" name="" value="search">
    </form>
</div>











<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>
