<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>User List</title>
</head>
<body>
<div class="container">
    <table class="table">
        <tr>
            <th>Email</th>
            <th>First name</th>
            <th>last name</th>
            <th>Username</th>
            <th>Image</th>
        </tr>
        <?php foreach($users as $key => $value): ?>
            <tr>
                <td><a href="index.php?route=userUpdateForm&email=<?=$value -> email?>"><?=$value -> email ?></a></td>
                <td><?=$value -> firstName ?></td>
                <td><?=$value -> lastName ?></td>
                <td><?=$value -> username ?></td>
                <td><a href="index.php?route=userDelete&email=<?=$value -> email?>&userId=<?=$key?>">Delete User</a></td>
                <td><img src="<?=$value -> image ?>" alt=""></td>
            </tr>
        <?php endforeach; ?>


    </table>
    <form class="" action="index.php?route=userListForm" method="">
        <input type="hidden" name="route" value="userListForm">
        <input type="text" name="emailFilter" value="">
        <input type="submit" name="" value="search">
    </form>
</div>











<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
