<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>appDemo</title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <div class="container resizedForm">
            <form action="index.php?route=<?php if (isset($article->title)): ?>articleUpdate<?php else: ?>articleCreate<?php endif; ?> " method="post">
                <div class="form-group text-center">
                    <h1><?php if (isset($article->title)) :?>Update Article<?php else: ?>Create Article<?php endif; ?></h1>
                    <label for="title">Title</label>
                    <input type="text" name="title" class="form-control" value="<?php if(isset($article->title)): echo $article->title; endif;?>">
                </div>
                <div class="form-group text-center">
                    <label for="description">Description</label>
                    <textarea class="form-control resizedTextArea" name="description"><?php if(isset($article->description)): echo $article->description; endif;?></textarea>
                <div class="form-group text-center">
                    <label for="body">Body</label>
                    <textarea class="form-control resizedTextArea" name="body"><?php if(isset($article->body)): echo $article->body; endif;?></textarea>
                </div>
                <div class="form-group text-center">
                    <label for="category">Category</label>
                    <select class="form-control" name="category">
                        <?php foreach($categories as $category): ?>
                                <option <?php if (isset($article->title) && $article->category === $category->category): echo 'selected="selected"'; endif?>> <?=$category -> category ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group text-center">
                    <label for="image">Upload image</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="form-group text-center">
                    <label for="user">Author of article</label>
                    <select type="text" name="user" class="form-control">
                        <?php if(isset($article->user)): echo "<option>" . $article->user . "</option>"; endif;?>">
                        <?php
                            foreach ($users as $user) {
                                printf("<option value='%s'>%s</option>",$user->username,$user->username);
                            }
                        ?>
                    </select>
                </div>
                <div class="form-group text-center">
                    <input type="submit" name="submit" value="<?php if (isset($article->title)): ?>Update Article<?php else: ?>Submit Article<?php endif; ?>">
                </div>

            </form>
        </div>





    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    </body>
</html>
